### ISSUE TITLE
커스텀 필드 생성 관련 질문 드립니다.

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#1]
안녕하세요. 세라젬-콘텐츠 커뮤니티 프로젝트의 이창호 개발자입니다.

다음 메서드 명세를 이용하려고 하고 io.rchemist.customer.data.CustomerCreateForm 데이터 클래스의 기본 파라미터 외에 커스텀 파라미터를 추가하려는 이슈입니다.
​
#회원 탈퇴 처리
ResponseData<Boolean> io.rchemist.customer.service.CustomerManageService.secedeCustomer(CustomerSecedeForm secedeForm)
​
#회원 정보 변경
ResponseData<Boolean> io.rchemist.customer.service.CustomerManageService.updateCustomer(CustomerUpdateForm form)
​
#회원 정보 생성
AuthenticationResponse io.rchemist.customer.security.service.CustomerAuthenticationService.requestRegister(CustomerCreateForm request)
​
io.rchemist.customer.data.CustomerCreateForm 데이터 클래스의
기본 프로퍼티 (회원아이디, 이름, 이메일, 비밀번호, 전화번호, 국가코드, 테넌트KEY, 사이트KEY 추가속성필드-attributes)
도 확인하였습니다. 
​
attribuets 의 타입이 해시맵이고 더미 해시맵이 바인딩 되어 있는데
​
여기에 키-벨류 값을 추가시 {"변수명":"값"} 형태로 추가하면 되는 것인가요?
​
그리고 추가적으로 커스텀 필드를 등록하는 프로세스가 더 있으면 관련한 패키지와 클래스를 알려주시면 감사하겠습니다.
​
감사합니다.

**Comment by kunner** [comment]
커스텀필드는 관리자도구에서 attribute 의 key 를 미리 선언해 두는 개념입니다.
엔티티에 정의되지 않은 필드값을 처리하기 위해 자유롭게 설정 가능한 Attribute 를 제공하는 것이고, 
이 값을 셋팅하는 방법은 커스텀필드 여부와 무관하게 동일합니다.


이해를 돕기 위해 소속 정보를 커스텀 필드로 설정하는 간단한 예를 들어 보겠습니다.

먼저, 소속에는 본사, 대리점, 외부 이렇게 세 가지 옵션값이 있다고 가정합니다.

1. 소속 값 처리를 위한 커스텀 옵션 생성
    이건 안해도 상관없지만, DB 에 ‘본사’ 값이 들어가는 것보다는 ‘A’ 같은 키워드가 들어가는게 더 낫겠죠.

    1) 관리자도구 - CONTENTS - Dynamic Contents - 커스텀 옵션으로 이동합니다.
    2) 커스텀 옵션을 등록합니다. 옵션의 Alias 를 'department_value' 로 지정합니다.
    2) 커스텀 옵션의 옵션값을 각각 다음과 같이 등록합니다.
       A - 본사
       B - 대리점
       C - 외부

2. 회원 정보에 소속 필드를 커스텀필드로 추가
   1) 관리자도구 - CONTENTS - Dynamic Contents - 커스텀필드 로 이동해 새 커스텀필드를 추가합니다.
   2) 대상 모듈에 회원을 선택하고 property name을 'department' 로 등록합니다.
   3) 필드타입을 '사용자정의 옵션 선택' 으로 선택하고 커스텀옵션 값에 'department_value' 를 입력합니다.

3. API 에서 Create/Update 할 때 단순 Key/Value 맵으로 해당 값을 전달합니다.
   예시) attribute.put('department', 'A');
   이렇게 하면 관리자도구에서 해당 회원의 소속 정보가 본사 로 표시됩니다.

**Comment by maketext** [comment]
커스텀 옵션의 property name가 attributes 해시맵 변수에서의 "키" 이고.
커스텀 필드의 속성이름도 attributes 해시맵 변수에서의 "키" 인가요?

커스텀 옵션의 Alias는 참고를 위한 단순 별칭으로 보아도 되는지요?

**Comment by maketext** [comment]
이해했습니다.

커스텀 필드에서 "속성 이름" 이 attributes 해시맵 변수의 "키" 이고
attributes 해시맵 변수의 "벨류" 는 플레인 텍스트여도 상관 없으나 규격화를 위해 커스텀 옵션 메뉴가 존재하는 것이지요?

그리고 커스텀 옵션 Alias (일종의 식별자)와 커스텀 필드에서의 필드타입-사용자정의 옵션 선택-커스텀옵션 값을 맞추면 연동이 되는 것이군요?

**Comment by kunner** [comment]
네 맞습니다. 관리자도구와 함께 사용해 보시면 더 쉽게 이해하실 수 있을 겁니다.
참고로, 오늘 중으로 관리자도구 새 빌드가 배포됩니다.

**Comment by maketext** [comment]
감사합니다. 커스텀 필드를 등록해야 한다면 현재 알케미스트 쪽의 서버 인스턴스에 접속하여 확인하고 있는데 여기에 커스텀 필드를 등록해도 되는지요?

**Comment by kunner** [comment]
네 테스트 목적으로 자유롭게 사용해도 됩니다. 
다만, 현재 배포 전 버전에서는 관리자도구에 약간 오류가 있을 수 있습니다.
만약 사용 중 오류가 발생하면 이슈 보드에 올려 주시면 조치 하겠습니다.

그리고 커스텀필드 관련한 추가 질문이 없다면, 이 이슈는 close 처리 하겠습니다.
