### ISSUE TITLE
안녕하세요. 배치 연동을 위해 질문을 드립니다.

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#2]
##### 스프링 배치 관련 질문입니다.
안녕하세요. 배치 연동을 위해 질문을 드립니다.

먼저 제가 파악한 배치 내용을 정리하려고 합니다.

배치의 흐름은 스케줄드-cron 어노테이션 스코프 -> Job 객체 -> Step 객체 (Tasklet) 

으로 파악했습니다.

기본적인 설정 객체들은 @EnableBatchProcessing 어노테이션 적용으로 빈 객체가 형성되며 오토와이어드로 참조할 수 있음을 확인했습니다.

- JobRepository: bean name "jobRepository"
- JobLauncher: bean name "jobLauncher"
- JobRegistry: bean name "jobRegistry"
- PlatformTransactionManager: bean name "transactionManager"
- JobBuilderFactory: bean name "jobBuilders"
- StepBuilderFactory: bean name "stepBuilders"

1. 메인컨텍스트 (@Scheduled)
```
@Scheduled(cron = "1 * * * * *")
public void JadeBatchMainActivity()
{
    JobExecution jobExecution = jobLauncher.run(jadeJob, parameters);
}
```
2. Job 객체
```
@Autowired
private Job jadeJob;
@Bean
public Job jadeJob()
{
    Job job = jobBuilderFactory.get("JadeJob")
        .start(makeTaskletStep())
        .build();

    return job;
}
```
3.  Step 객체
```
private Step makeTaskletStep()
{
    return stepBuilderFactory.get("jadeBatchTaskletStep")
        .tasklet((contribution, chunkContext) -> {
            //비즈니스 로직

        return RepeatStatus.FINISHED;
        }).build();
}
```
궁금한 점은 런처를 통해서 잡을 런 할 때,
```
JobExecution jobExecution = jobLauncher.run(ExampleJob, parameters);
```
다음과 같이 잡 레파지토리를 만들어 장착해야 하는지 궁금합니다.
```
@Override
protected JobRepository createJobRepository() throws Exception {
    JobRepositoryFactoryBean factory = new JobRepositoryFactoryBean();
    factory.setDataSource(dataSource);
    factory.setTransactionManager(transactionManager);
    factory.setIsolationLevelForCreate("ISOLATION_SERIALIZABLE");
    factory.setTablePrefix("BATCH_");
    factory.setMaxVarCharLength(1000);
    return factory.getObject();
}

@Bean
public JobLauncher jobLauncher() {
	SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
	jobLauncher.setJobRepository(jobRepository());
	jobLauncher.setTaskExecutor(new SimpleAsyncTaskExecutor());
	jobLauncher.afterPropertiesSet();
	return jobLauncher;
}
```
그리고 관련하여 DB에 연동해야 할 경우 관련한 스키마가 있는지 궁금하고 만약 없거나 필요치 않으시다면 setDataSource 함수 반환값을 void로 하여 다음과 비슷하게 스킵해 보도록 하겠습니다.
```
@Configuration
@EnableAutoConfiguration
@EnableBatchProcessing
public class BatchConfiguration extends DefaultBatchConfigurer {

    @Override
    public void setDataSource(DataSource dataSource) {
        // override to do not set datasource even if a datasource exist.
        // initialize will use a Map based JobRepository (instead of database)
    }

}
```

감사합니다.

**Comment by kunner** [comment]
SpringBoot 에서는 @EnableScheduling 과 @Scheduled 를 이용해 자동으로 스케쥴러를 관리할 수 있습니다.
별도의 Job 이나 Batch 프로세스를 개발할 필요가 없습니다.
그냥 SpringBoot 어플리케이션에서 @EnableScheduling 을 걸고 반복이 필요한 서비스 메소드에 @Scheduled 를 걸어 주시면 됩니다.
항상 같은 시각에 실행해야 하니 cron 으로 걸어 주면 되겠고, 
만약 멀티 인스턴스 환경에서 중복 처리가 되지 않게 하려면 특정 저장소에(redis 같은) 마지막 실행 시각 저장하고 확인하는 정도면 충분하겠죠.
@EnableScheduling 관련한 내용은 검색해 보시면 자료가 풍부하니 참고하시기 바랍니다.

추가로, 이 질문은 저희 플랫폼 관련 내용이 아니므로 close 처리 하겠습니다.
