### ISSUE TITLE
CustomerManageService, CustomerAuthenticationService 관련 질문입니다.

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#3]
안녕하세요.
​
세라젬 콘텐츠-커뮤니티 프로젝트의 이창호 개발자입니다.​
​
세라젬 프로젝트에서 아이디는 이메일이라고 합니다. 그리고 고유값이라고 합니다.
​
회원 등록시 username과 emailAddress 필드 값을 비워둘 수 없어 세라젬 이메일 값으로 똑같이 채워 넣으려고 합니다.
​
1. 한 계정당 username과 emailAddress 필드값이 같아도 되는지요.​
​
2. CustomerUpdateForm의 id 와 CustomerSearchForm의 customerId 필드 그리고 CustomerSecedeForm.SecedeForm의 customerId 필드는 고유값으로 판단이 됩니다.

update와 secede시에 customerid를 주입해야 하는데  searchCustomers 로 찾아서 주입하는 것이 맞는지요?
​
감사합니다.

**Comment by kunner** [comment]
각 항목에 답변 드립니다.

1. 두 값은 같아도 상관 없습니다.
2. customerId 는 플랫폼 내부적으로 관리하는 키값 입니다.
  기본적으로 업데이트, 탈퇴 시 자신의 정보를 사용하기 때문에 SecurityContextResolver.getAuthentication().getUserId(); 로 자신의 CustomerId 를 얻을 수 있습니다. 다만, 배치의 경우에는 CustomerSearchForm 에 emailAddress 나 username 으로 검색한 후 해당 결과값으로 CustomerId 를 식별하면 됩니다.

**Comment by maketext** [comment]
> 

감사합니다. 배치의 경우로 개발 중에 있습니다. 이슈를 닫겠습니다. 감사합니다.
