### ISSUE TITLE
커스텀 필드 추가와 관련된 함수에 대한 질문입니다.

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#4]
io.rchemist.customer.data.CustomerCreateForm 클래스를 이용해 신규 입사자를 CREATE 하려고 합니다.
io.rchemist.customer.data.CustomerUpdateForm 클래스를 이용해 퇴직 직원을 UPDATE 하려고 합니다.

다음 두 어트리뷰트 생성 함수는 커스텀 필드와 관련된 함수로 예상이 됩니다. 
예상이 맞다면 질문 드리겠습니다.

DTO를 넣거나 String 값을 넣는 두 가지 경우가 있습니다.

1. 다음 함수의 키 벨류는 속성 이름과 값인가요?
void io.rchemist.customer.data.CustomerCreateForm.setAttributes(final Map<String, String> attributes)

2. 다음 함수 내에서 put을 하는데 dto 객체로 put을 하고 있습니다. 마찬가지로 DTO의 Name은 속성 이름이고 DTO의 Value는 값인가요?
public io.rchemist.customer.data.CustomerUpdateForm addAttribute(AttributeDTO dto) {
  this.attributes.put(dto.getName(), dto);
  return this;
}

**Comment by kunner** [comment]
네, 둘 다 맞습니다.

update 일 때 단순 Map<String, String> 이 아닌 이유는 Attribute 의 ID 값이 필요하기 때문입니다.
AttributeDTO.id 에 CustomerAttribute.id 값이 필요합니다.
id 값이 없으면 새 row로 들어가게 됩니다.

**Comment by maketext** [comment]
답변 감사합니다. 추가  질문 드립니다.

관리자페이지에서 커스텀필드 추가시 필수값 여부를 아니오로 하고 (체크하지 않음),

1. 어트리뷰트를 추가할 때 아래와 같이 null 값을 넣어도 되는지요. 신규 입사자에 대해 퇴직일 Date 타입 값을 null 로 하려고 합니다.
```
createForm.addAttribute("RetireDate", null);
``` 

2. 위의 답변 주신 내용을 참고하여 Attribute의 ID 값을 찾아오려고 했으나 불가능하거나 번거롭다고 판단이 되어 아래와 같이 어트리뷰트 맵 객체를 통으로 가져와서 각 맵 키-벨류 엘리먼트 쌍을 그 안에서 불러와 put 하려고 합니다. 이러면 Attrubte ID 값이 기존 ID 값으로 되어 새 row 가 생기지 않는 것 같습니다. 맞다고 생각하시는지요?
```

Map<String, AttributeDTO> attributes = 기존 customerDTO를 포함한 CustomerUpdateForm 객체로부터 반환
attributes.put("RetireDate", attributes.get("RetireDate").withName("RetireDate").withValue(registerRequest.getRETIREYMD()));
attributes.put("StateName", attributes.get("StateName").withName("StateName").withValue(registerRequest.getSTATNM()));
```

**Comment by kunner** [comment]
1. 빈 값을 입력할 경우 아예 입력하지 않으면 됩니다. 기존에 입력된 값을 지우고 싶다면 "" 로 값을 변경합니다. 

2. 네 그렇게 사용하시면 됩니다.

**Comment by maketext** [comment]
커스텀필드 RetireDate는 관리자도구에서 커스텀필드 추가시 "날짜" 타입으로 지정하였습니다.

아래와 같은 실제 구현부에서,
```
Map<String, AttributeDTO> attributes = 기존 customerDTO를 포함한 CustomerUpdateForm 객체로부터 반환
attributes.put("RetireDate", attributes.get("RetireDate").withName("RetireDate").withValue(registerRequest.getRETIREYMD()));
```
getRETIREYMD() 함수는 Date 타입을 리턴하도록 하였습니다.

withValue 함수는 String 타입을 입력하도록 정의되어 있습니다. 커스텀필드 유형에서 "날짜" 타입으로 정의하였기에 날짜 타입으로 값을 입력하고 싶습니다. Date 객체의 yyyyMMdd 포멧 형식으로 입력할까요? getTime() 함수를 이용해 long 형으로 입력할까요?

감사합니다.

**Comment by kunner** [comment]
커스텀필드에서 날짜 타입의 경우는 ISO LocaldateTime 포맷을 사용합니다. 자바 코드에서는 LocalDateTimeUtil.format(LocalDateTime) 을 사용하시면 됩니다.

**Comment by kunner** [comment]
시각을 포함하지 않는 날짜의 경우는 LocalDate 이며 이 경우는 LocalDateUtil.format() 을 쓰시면 됩니다.

**Comment by maketext** [comment]
감사합니다. 클로즈 하겠습니다.
