### ISSUE TITLE
운영 어드민 회원관리 검색 문제

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#6]
안녕하세요.

톡톡 운영 서버의 어드민 페이지에 검색 기능이 좀 불완전 한 것 같습니다.

메뉴 CUSTOMER > 회원 > 회원관리
1. 페이지네이션 1페이지에서  Search 아이디 검색 기능이 정상 동작하나 2페이지 3페이지를 보면서 검색했을 때는 아이디 검색 기능이 동작 안함.

2. 필터 기능을 사용해 OR 조건 검색시 이름 전화번호 등을 기입하여 검색하면 중복 검색됨. 동일 회원인데 3개 항목으로 검색되는 경우가 많음.

2-1. 다시 페이지네이션을 1페이지로 하고 동일인을 Username 으로 검색하면 1명만 정상적으로 검색됨.

**Comment by kunner** [comment]
목록 표시 관련 기능이 전반적으로 변경되었습니다. 어제 저녁 배포 후 문제가 해결됐으리라 생각되는데, 확인 부탁 드립니다.

**Comment by maketext** [comment]
1. 여전히 페이지네이션 2페이지 이상을 펼쳐놓고  "Search 아이디" inputbox로 검색하면 검색 결과가 없습니다. 다만 보통 "Search 아이디" inputbox를 1페이지에서 검색할 것이므로 문제는 없어보입니다.


2. 중복 검색되는 문제는 해결되었습니다.

클로즈 처리하겠습니다.

**Comment by hongin81** [comment]
해당 부분이 어제 배포가 되지 않아 금일 6시 배포 예정입니다.

**Comment by hongin81** [comment]
해당 오류 수정 배포완료했습니다. 확인 부탁 드립니다.

**Comment by maketext** [comment]
정상 처리됩니다. 클로즈 하겠습니다.
