### ISSUE TITLE
커스텀 필드 Date타입 로우 스트링 'T' 포함여부

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-admin-mono#7]
안녕하세요.

DB 이관을 프론트 프로젝트 (demo-micro-front-mono) 에서 진행하고 있습니다. 배치 소스코드를 다듬어서 어드민 프로젝트 쪽에 푸시할 예정입니다.

아래와 같이 파싱하여 값을 스트링으로 변경하여 어트리뷰트 데이터 클래스에 주입했습니다.
```
// registerRequest.getENTERYMD()의 함수는 YYYYMMDD 포멧의 값을 리턴함
// 생성의 경우
createForm.addAttribute("EnterDate", LocalDateTimeUtil.format(registerRequest.getENTERYMD().atStartOfDay()));

//수정의 경우
attributeDTO.setValue(LocalDateTimeUtil.format(registerRequest.getENTERYMD().atStartOfDay()));
```
그런데 DB 상에 값이 YYYYMMDD'T'HHmmss 형식으로 되어 있습니다. 이는 일반적인 DateTime 필드의 포멧 YYYYMMDD HHmmss와 가운데 캐릭터 부분이 다릅니다. 

따라서 어드민에서 회원 상세 조회를 했을 때 날짜 타입 커스텀 필드 값이 어드민 홈페이지 프론트 사이드에서 주입되지 않는 것 같습니다.

제가 잘못 이해한 것이라면 바로잡아 주십시오. 감사합니다.

**Comment by kunner** [comment]
먼저, 커스텀필드가 DB 에 저장되는 방식은 단순 String(varchar) 입니다.

이렇게 저장된 값을 어떻게 사용하는가는 철저히 어플리케이션의 문제고요. 따라서 일반적인 DateTime  필드 포맷과는 관계가 없습니다.

LocalDateTimeUtil.format 을 사용하면 Java 의 LocalDateTime.ISO_OFFSET_DATE_TIME 형태로 저장됩니다.

이걸 다시 어플리케이션에서 꺼내서 LocalDateTime 형태로 변환하거나, 다른 날짜의 경우 거기에 맞는 Formatter 를 설정해 변환하면 됩니다.

LocalDateTimeUtil.parse(value, LocalDateTime.ISO_OFFSET_DATE_TIME) 같은 형태가 되겠죠.


LocalDateTime 포맷에 대한 추가 정보는 https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_OFFSET_DATE_TIME 를 참고해 주세요.
